bring zope.conf into the build
GSS-Cogs/dd-cms pull request #804
Opened 2023-02-01 16:16 UTC by mikeAdamss

## What is this

Currently the `zope.conf` (and the database credentials) are being injected into the container during deployment via k8s, so we're ending up with a build that's not very representative of live, it's also a pain to run locally as critical configuration is missing.

This PR moves the `zope.conf `out of the IAC and into the build and does some (not as clean as I'd like) build arg trickery so that the `zope.conf` is populated correctly per-environment and can be populated correctly when running locally against a postgres instance running via docker.

Have included how to run a local docker plone and local docker postgres from a cloudsql export in the README. Have not touched on accessing postgres local with a non containerised plone as that'll be something else again.

## Additional Info

My preference would have been env vars rather than the hacky `sed` but plone has opinions.

**Important** -  when or if we're happy with this approach it can only be merged in tandem with IAC cloud build changes to provide the required build args for staging as well as IAC changes to not inject `zope.conf` via k8s anymore.

This doesn''t touch on tests as (I think) they're running against a local file store plone. This doesn't resolve that but doesn't make it worse.

## How to test

Pull repo and try procedure as outlined in the README. If it works and we're happy with this the cloud build and IAC changes will  need to be a separate task.

2023-02-02 12:37 UTC, mikeAdamss commented
just occurred to me we might not want to merge this until prod IAC is in 😩 as we'll have to update the old k8s configs for production as well and I don't know if we want to risk it. 70% sure it'd be fine, don't know if 70% is worth it.

2023-02-02 16:07 UTC, eldeal requested changes
Couple of documentation updates and typo fixes is all. Very helpful overall!!

2023-02-02 16:26 UTC, mikeAdamss commented on plone-5/README.md
> +| POSTGRES_HOST | The IP address of the database | An internal GCP IP address in the appropriate VPC, named `<env>-db-internal` |
no you're right, I'll change it in the IAC and update this doc when I do.

2023-02-02 16:29 UTC, mikeAdamss commented on plone-5/README.md
> +docker run --name plone-postgres -d -p 5432:5432 postgres:14
will update to a more explicit approach, it'll probably be easier for future folks to grep what's going on without the env vars anyway

2023-02-06 15:06 UTC, mikeAdamss commented on plone-5/README.md
> +| POSTGRES_HOST | The IP address of the database | An internal GCP IP address in the appropriate VPC, named `<env>-db-internal` |
for now I've removed the reference to the ip address name as I don't wan't this PR blocked waiting on the next round of IAC changes. I will change the naming convention though.

2023-02-06 15:12 UTC, mikeAdamss commented
pr comments addressed.

it might not be where it lives in the future, but for now I've added a brief additional comment with the command to connect a local volto the the local plone setup described in the README.

2023-02-07 11:42 UTC, eldeal approved these changes

2023-02-08 17:39 UTC, merged